<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.github.jothammicheni</groupId>
	<artifactId>daraja-sdk</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>

	<name>Daraja M-Pesa SDK (Parent)</name>
	<url>https://github.com/jothammicheni/daraja-sdk</url>

	<modules>
		<module>core</module>
		<module>android</module>
	</modules>

	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<micrometer.version>1.13.2</micrometer.version>
		<prometheus.version>1.3.1</prometheus.version>
	</properties>

	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>jothammicheni</id>
			<name>Jotham Micheni</name>
			<email>your-email@example.com</email>
			<organization>GitHub</organization>
			<organizationUrl>https://github.com/jothammicheni</organizationUrl>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:git://github.com/jothammicheni/daraja-sdk.git</connection>
		<developerConnection>scm:git:ssh://github.com/jothammicheni/daraja-sdk.git</developerConnection>
		<url>https://github.com/jothammicheni/daraja-sdk</url>
	</scm>

	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
	</distributionManagement>
</project>